apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortner
  name: url-shortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortner
  strategy: {}
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - image: archit05/url-shortner:1.0.0
          name: url-shortner
          resources: {}
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: my-mysql
                  key: mysql-root-password
status: {}