apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-shortner
  name: url-shortner
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: url-shortner
  type: NodePort
status:
  loadBalancer: {}
